### ISSUE TITLE
Compile code

### ISSUE THREAD

**Issue by nnoromuche** [davidenq/coditor#1]
Hi David! This is fantastic! I was wondering how one could compile the source code (retrieved from the editor) using jquery or angular js. This would be very helpful. Thank you and well done!

**Comment by davidenq** [comment]
@Nnoromuche 

Coditor is just a acejs-based editor of code with a some extra features (multitab).  For compile your source code retrieved from the editor, you should send your code via ajax or html form (or another mechanism such as tcp, upd, websockets)  to the backend(php, nodejs, java, etc) to compile and retrieve a result.
I'm not sure, but you can't compile multiples languages in frontend with jquery or angular or other library because, languages like java or c# not are interpreted such as javascript, python or php, they needs to be compiled.

 I hope that I've been able to help resolve your doubts

**Comment by nnoromuche** [comment]
Hi David, thank you for the explanation :)
